- hosts: base
  become: true
  tasks:
    - name: Install Guest Addon
      shell: |
        mount -r -t iso9660 /dev/cdrom /media
        /media/VBoxLinuxAdditions.run
        umount /media
        eject
      args:
        warn: no

    - name: Finalize viartualboxize
      shell: |
        mkdir -p /vagrant
        yum clean all
        rm -rf /var/cache/yum
        history -c
      args:
        warn: no

    - debug:
        msg:
        - "next: make box"
